### ISSUE TITLE
Support Linux and OSX

### ISSUE THREAD

**Issue by chinesedfan** [Rob--/memoryjs#18]
Now it only supports Windows. Is it possible to support other operating systems? Or can you list some reading materials about process memory reading? Thanks all the same.

**Comment by Rob--** [comment]
Looks like this is what you're looking for: https://github.com/luser/read-process-memory

**Comment by chinesedfan** [comment]
@Rob-- Thanks for your link. But it is written in Rust. I don't know how to import it by npm.

Share you with a Linux C API, http://man7.org/linux/man-pages/man2/process_vm_readv.2.html. Maybe it can integrated into this package.

**Comment by Rob--** [comment]
Unfortunately I'm not interested in supporting Linux/OSX right now, sorry!

**Comment by T-vK** [comment]
Please mention in the readme that this is for windows only. It would also make sense to have it directly in the description of the repository. Thanks

**Comment by Rob--** [comment]
Sure thing @T-vK, I'll make that edit soon. I will also try and look into Linux/OSX support though, this could probably be achieved quite easily through a series of pre-processor directives.

**Comment by T-vK** [comment]
That would be amazing! 
In that case something else I would love to see, is support for kvm. As in, access the memory of a virtual machine running in kvm, as seen here: https://www.unknowncheats.me/forum/anti-cheat-bypass/294856-kvm-dma-library.html
So if you add support for Linux/OSX it would be nice if you kept that door open so that something like that could  be added in the future.

**Comment by jakiestfu** [comment]
Would love mac support as well!
