### ISSUE TITLE
Does VAC detect this?

### ISSUE THREAD

**Issue by MelerEcckmanLawler** [Rob--/memoryjs#45]
I'm not sure where else to ask this, but if I were to use this to READ (but NOT write) memory of a Steam online multiplayer game, would I get banned?  Can VAC "know" if I'm reading a game's memory?

I am not cheating by the way.

**Comment by Rob--** [comment]
I have not known VAC to ever ban for opening a handle to a process or for simply just reading game memory, but this could change at any time and may have already changed since I was last familiar with playing around with games that use VAC. You are probably safe, but just be careful and use alternative accounts where possible.

**Comment by MelerEcckmanLawler** [comment]
Okay thanks!  If I happen to get banned I will let you know, I'm sure users would be curious.  If I don't report back, assume I didn't get banned haha.

**Comment by xetrics** [comment]
For future googlers because I'm sure this question will rise a lot...

VAC is mostly just a signature scanner. Simply reading/writing memory and opening handles will not get you banned. You only run into problems when you copy code from sources found online that VAC has generated a signature for.

A prime example is the blackbox code for generating angles for aimbot in CSGO that has been shared around online for several years.
