### ISSUE TITLE
readBytes memory leaking

### ISSUE THREAD

**Issue by slauko** [Rob--/memoryjs#69]
like the title says , 
id like to read chunks of memory but readBytes just leaking memory so i need to read 1000x for an array of DWORDs instead just once a bigger chunk and get the DWORDS from the bytes :/
pretty much unperformant that way

**Comment by Rob--** [comment]
Do you mean `readBuffer`? Are you trying to read an array of DWORDS?

**Comment by bumpmann** [comment]
I also had the issue but i am not sure how to resolve this. 

Here is my work but i m stuck with the Napi::Buffer<char>::New not working well
https://github.com/bumpmann/memoryjs/commit/5bbd73b099055f137c5c668d8729532205eda01c

**Comment by slauko** [comment]
> Do you mean `readBuffer`? Are you trying to read an array of DWORDS?

ehh yes sorry readBuffer .. 
i tried reading a dword array in like 20000bytes and then convert the byte array to dwords since this would just be 1 read instead 5k reads

but yes the readBuffer method was leaking had like 1gb ram usage after 1 sec :D

**Comment by Rob--** [comment]
Fixed in b6b328a.

@bumpmann see my [code comment](https://github.com/Rob--/memoryjs/commit/b6b328aea8932fc1dc8cca138b2194c92ac94bac#diff-7cdc5f6c2b3d8580bf61ff3fdac0b98bf51e77853f3810e259400e5ce51c2752R506) for details about the problem with `Napi::Buffer::New`. Your solution was right, use `Buffer::Copy` and manually free the memory.

**Comment by nanchengjiumeng** [comment]
@Rob-- I solved the problem with your new code, but it's still the old code on NPM. Can you update the version of npm?
