### ISSUE TITLE
Issues with Strings and Exception Handling

### ISSUE THREAD

**Issue by tuefekci** [Rob--/memoryjs#8]
Hey mate, really like this but i have problems with the string format and errors.

If i use string as type it just dies and even if i set a data type which not exists it also just dies i never get an error. (using async callback if i just use it static it thwrows one for unknown data type but not for string)

Everything else works nice Win10 x64.

I read in the other issue you dont have much time for this anymore but i would love to get a fix for this cause i am at the moment dont have the skills to debug it myself.

Thanks

**Comment by tuefekci** [comment]
found an ugly workaround need to figure out when i slept some more how to do it propper

**Comment by Rob--** [comment]
Hey, if you could post the code you were having problems with before and your solution that would be really helpful for me, you don't have to though :)

Glad to hear you got it working though, the library definitely needs an update so I'll look into that sometime if I can.

**Comment by tuefekci** [comment]
Hey Rob-- nice to hear from you i am still experimenting with it so i am not an c++ developer at all my fix for strings was to add a read string function into memory.h theres probably a way of fixing it with the standart read function but i could not figure out how.

`	char* readStringFromMemory(HANDLE hProcess, DWORD dwAddress) {
        char value[255];
		ReadProcessMemory(hProcess, (LPVOID)dwAddress, value, 255, NULL);
		return value;
	}
`

this hotfixed it for my use case but i really dont wanne push it ^^

i am now trying to figure out how to propperly read out a 64bit process base adress because it looks like the standart gives me only 32 bit stuff ^?

Sorry for my english mate, i really like this node gives you some options if you wanne poke aroung in other processes without having the whole compiling and aplication step between would love an update for the libary would like to help but i am still to novice with all the memory stuff.

**Comment by Rob--** [comment]
Hey @tuefekci , I was playing around earlier today with a working implementation to write strings, so I will probably update the library soon. I will also have a look at a proper implementation to reading strings.

I've never actually tried using this library to interact with a 64 bit process so I took a quick look and from what I can see so far the library can handle interacting with the process but I think the limitation occurs with memory addresses. I'm just guessing this because I can write memory to a 32bit app, but not a 64bit app.
